apiVersion: v1
kind: Service
metadata:
  name: windows-resource
  namespace: windows
spec:
  selector:
    app: windows-resource-kit
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30008