apiVersion: batch/v1
kind: Job
metadata:
  name: ib-job
  namespace: tkw-system
spec:
  template:
    spec:
      containers:
        - name: ibcontainer
          image: projects-stg.registry.vmware.com/tkg/image-builder:v0.1.13_vmware.2
          volumeMounts:
            - name: volume-config
              mountPath: "/home/imagebuilder/config"
          args: ["build-node-ova-vsphere-windows-2019"]
      restartPolicy: Never
      volumes:
      - name: volume-config
        configMap:
          name: ib-windows
          items:
            - key: windows.json
              path: windows.json
  backoffLimit: 4