# permissions for end users to edit osimages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: osimage-editor-role
rules:
- apiGroups:
  - imagebuilder.tanzu.opssec.in
  resources:
  - osimages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - imagebuilder.tanzu.opssec.in
  resources:
  - osimages/status
  verbs:
  - get
